### ISSUE TITLE
Collaboration invitation

### ISSUE THREAD

**Issue by brunolnetto** [robmclarty/cred-server#20]
Hi fellow,

Firstly, I stumbled upon your projects because they are legit and very clear. Then, this repository is very close to my own effort to write [a server template](https://github.com/web-needle/sappio). I suggest we bring efforts together to enhance community knowledge.

**Comment by robmclarty** [comment]
hey @brunolnetto,

Thanks for your interest! Unfortunately I can't afford to work on this atm, but I'll be creating a new express app template soon which combines the techniques I've been honing with `storium` and `cred` (2 other projects that may interest you). I'm currently busy building out a new company along with 2 new web app products so my time is mostly used up doing that. But thanks for reaching out, and look forward to what you come up with!

- https://github.com/robmclarty/cred
- https://github.com/robmclarty/storium
